### ISSUE TITLE
Need to pass in environment variables to BillSim

### ISSUE THREAD

**Issue by amprokop** [aih/billsim#18]
For a Library of Congress project, we need to connect to Postgres on port 5433, not port 5432.

The billsim code doesn't seem to use the values defined in the .env file at the top-level. I thought it did use those .env values, but potentially I hardcoded port 5433 into the billsim package and forgotten it, then reinstalled billsim and wiped that change away.

How can we best pass the postgres port and host into the billsim package? Potentially we should pass it at runtime rather than as an env variable? Or is there some way to have the billsim package use the .env file at the top level of the repo? This would appear to be an issue for any user of the billsim package, as generally you'd want to pass in username/password/etc and not use defaults.

**Comment by aih** [comment]
@amprokop this library *does* use the environment variables set at any level. However, it doesn't use the `.env` file from a parent library, because that is not accessible to this one (it has to be added to a script locally, e.g. with the dotenv package). So in the parent repo you should be able to export the variables to the global environment (see https://gist.github.com/mihow/9c7f559807069a03e302605691f85572) before importing billsim

@Miaskad and @[alexbojko](https://github.com/Miaskad), what do you think? Is there another way to pass environment variables to an imported library?

**Comment by amprokop** [comment]
After more investigation, I found the more accurate source of my issues:

I had the billsim library installed in multiple places, and the .env variables were set to the correct values in the wrong place.

Closing since it appears no changes are needed.
